# Generated by Django 5.2.6 on 2025-09-14 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibemedia',
            name='file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
