# Generated by Django 5.2.6 on 2025-09-18 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0002_alter_vibemedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibe',
            name='media',
            field=models.FileField(default=1, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv'])]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VibeMedia',
        ),
    ]
