# Generated by Django 5.2.6 on 2025-09-18 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0003_vibe_media_delete_vibemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibe',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
